from enum import Enum

class Stage(Enum):
    STAGE_BATTLE_FIELD=1
    STAGE_FINAL_DESTINATION=4
    STAGE_POKEMON_STADIUM2=41
    STAGE_SMASH_VILLE=45
    STAGE_HANENBOW=55
    STAGE_TOWN_AND_CITY=86

class Fighter(Enum):
    FIGHTER_MARIO = 0
    FIGHTER_DONKEY = 1
    FIGHTER_LINK = 2
    FIGHTER_SAMUS = 3
    FIGHTER_YOSHI = 4
    FIGHTER_KIRBY = 5
    FIGHTER_FOX = 6
    FIGHTER_PIKACHU = 7
    FIGHTER_LUIGI = 8
    FIGHTER_NESS = 9
    FIGHTER_CAPTAIN = 10
    FIGHTER_PURIN = 11
    FIGHTER_PEACH = 12
    FIGHTER_KOOPA = 13
    FIGHTER_POPO = 14
    FIGHTER_NANA = 15
    FIGHTER_SHEIK = 16
    FIGHTER_ZELDA = 17
    FIGHTER_MARIOD = 18
    FIGHTER_PICHU = 19
    FIGHTER_FALCO = 20
    FIGHTER_MARTH = 21
    FIGHTER_YOUNGLINK = 22
    FIGHTER_GANON = 23
    FIGHTER_MEWTWO = 24
    FIGHTER_ROY = 25
    FIGHTER_GAMEWATCH = 26
    FIGHTER_METAKNIGHT = 27
    FIGHTER_PIT = 28
    FIGHTER_SZEROSUIT = 29
    FIGHTER_WARIO = 30
    FIGHTER_SNAKE = 31
    FIGHTER_IKE = 32
    FIGHTER_PZENIGAME = 33
    FIGHTER_PFUSHIGISOU = 34
    FIGHTER_PLIZARDON = 35
    FIGHTER_DIDDY = 36
    FIGHTER_LUCAS = 37
    FIGHTER_SONIC = 38
    FIGHTER_DEDEDE = 39
    FIGHTER_PIKMIN = 40
    FIGHTER_LUCARIO = 41
    FIGHTER_ROBOT = 42
    FIGHTER_TOONLINK = 43
    FIGHTER_WOLF = 44
    FIGHTER_MURABITO = 45
    FIGHTER_ROCKMAN = 46
    FIGHTER_WIIFIT = 47
    FIGHTER_ROSETTA = 48
    FIGHTER_LITTLEMAC = 49
    FIGHTER_GEKKOUGA = 50
    FIGHTER_PALUTENA = 51
    FIGHTER_PACMAN = 52
    FIGHTER_REFLET = 53
    FIGHTER_SHULK = 54
    FIGHTER_KOOPAJR = 55
    FIGHTER_DUCKHUNT = 56
    FIGHTER_RYU = 57
    FIGHTER_CLOUD = 58
    FIGHTER_KAMUI = 59
    FIGHTER_BAYONETTA = 60
    FIGHTER_INKLING = 61
    FIGHTER_RIDLEY = 62
    FIGHTER_SIMON = 63
    FIGHTER_KROOL = 64
    FIGHTER_SHIZUE = 65
    FIGHTER_GAOGAEN = 66
    FIGHTER_PACKUN = 67
    FIGHTER_JACK = 68
    FIGHTER_BRAVE = 69
    FIGHTER_BUDDY = 70
    FIGHTER_DOLLY = 71
    FIGHTER_MASTER = 72
    FIGHTER_TANTAN = 73
    FIGHTER_PICKEL = 74
    FIGHTER_EDGE = 75
    FIGHTER_MIIFIGHTER = 76
    FIGHTER_MIISWORDSMAN = 77
    FIGHTER_MIIGUNNER = 78
    FIGHTER_SAMUSD = 79
    FIGHTER_DAISY = 80
    FIGHTER_LUCINA = 81
    FIGHTER_CHROM = 82
    FIGHTER_PITB = 83
    FIGHTER_KEN = 84
    FIGHTER_RICHTER = 85
    FIGHTER_KOOPAG = 86
    FIGHTER_MIIENEMYF = 87
    FIGHTER_MIIENEMYS = 88
    FIGHTER_MIIENEMYG = 89

class Direction(Enum):
    NONE = 0
    UP = 1
    UP_RIGHT = 2
    RIGHT = 3
    DOWN_RIGHT = 4
    DOWN = 5
    DOWN_LEFT = 6
    LEFT = 7
    UP_LEFT = 8

class Button(Enum):
    NONE = 0
    A = 1
    B = 2
    X = 4
    Y = 8
    L_STICK_BUTTON = 16
    R_STICK_BUTTON = 32
    L = 64
    R = 128
    ZL = 256
    ZR = 512
    PLUS = 1024
    MINUS = 2048
    D_PAD_LEFT = 4096
    D_PAD_UP = 8192
    D_PAD_RIGHT = 16384
    D_PAD_DOWN = 32768

class Action:
    NONE = 0
    JAB = {"name": "JAB", "buttons": [Button.BUTTON_A], "main_stick": (0, 0), "c_stick": (0, 0), "hold": False}
    RIGHT_TILT = {"name": "RIGHT_TILT", "buttons": [Button.BUTTON_MODIFIER, Button.BUTTON_S_RIGHT, Button.BUTTON_A], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    LEFT_TILT = {"name": "LEFT_TILT", "buttons": [Button.BUTTON_MODIFIER, Button.BUTTON_S_LEFT, Button.BUTTON_A], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    UP_TILT = {"name": "UP_TILT", "buttons": [Button.BUTTON_MODIFIER, Button.BUTTON_S_UP, Button.BUTTON_A], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    DOWN_TILT = {"name": "DOWN_TILT", "buttons": [Button.BUTTON_MODIFIER, Button.BUTTON_S_DOWN, Button.BUTTON_A], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    RIGHT_SMASH = {"name": "RIGHT_SMASH", "buttons": [Button.BUTTON_S_RIGHT, Button.BUTTON_A], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    LEFT_SMASH = {"name": "LEFT_SMASH", "buttons": [Button.BUTTON_S_LEFT, Button.BUTTON_A], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    UP_SMASH = {"name": "UP_SMASH", "buttons": [Button.BUTTON_S_UP, Button.BUTTON_A], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    DOWN_SMASH = {"name": "DOWN_SMASH", "buttons": [Button.BUTTON_S_DOWN, Button.BUTTON_A], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    NEUTRAL_SPECIAL = {"name": "NEUTRAL_SPECIAL", "buttons": [Button.BUTTON_B], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    RIGHT_SPECIAL = {"name": "RIGHT_SPECIAL", "buttons": [Button.BUTTON_S_RIGHT, Button.BUTTON_B], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    LEFT_SPECIAL = {"name": "LEFT_SPECIAL", "buttons": [Button.BUTTON_S_LEFT, Button.BUTTON_B], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    UP_SPECIAL = {"name": "UP_SPECIAL", "buttons": [Button.BUTTON_S_UP, Button.BUTTON_B], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    UP_RIGHT_SPECIAL = {"name": "UP_RIGHT_SPECIAL", "buttons": [Button.BUTTON_S_UP, Button.BUTTON_S_RIGHT, Button.BUTTON_B], "hold": False, "sec": 0.05, "wait": 0.05, "refresh": False}
    UP_LEFT_SPECIAL = {"name": "UP_LEFT_SPECIAL", "buttons": [Button.BUTTON_S_UP, Button.BUTTON_S_LEFT, Button.BUTTON_B], "hold": False, "sec": 0.05, "wait": 0.05, "refresh": False}
    DOWN_SPECIAL = {"name": "DOWN_SPECIAL", "buttons": [Button.BUTTON_S_DOWN, Button.BUTTON_B], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    GRAB = {"name": "GRAB", "buttons": [Button.BUTTON_R], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    GUARD = {"name": "GUARD", "buttons": [Button.BUTTON_ZR], "hold": True, "sec": 0.02, "wait": 0.05, "refresh": False}
    JUMP = {"name": "JUMP", "buttons": [Button.BUTTON_Y], "hold": True, "sec": 0.02, "wait": 0.05, "refresh": True}
    RIGHT_JUMP = {"name": "RIGHT_JUMP", "buttons": [Button.BUTTON_S_RIGHT, Button.BUTTON_Y], "hold": True, "sec": 0.02, "wait": 0.05, "refresh": True}
    LEFT_JUMP = {"name": "LEFT_JUMP", "buttons": [Button.BUTTON_S_LEFT, Button.BUTTON_Y], "hold": True, "sec": 0.02, "wait": 0.05, "refresh": True}
    SHORT_HOP = {"name": "SHORT_HOP", "buttons": [Button.BUTTON_Y, Button.BUTTON_X], "hold": True, "sec": 0.02, "wait": 0.05, "refresh": True}
    RIGHT_SHORT_HOP = {"name": "RIGHT_SHORT_HOP", "buttons": [Button.BUTTON_S_RIGHT, Button.BUTTON_Y, Button.BUTTON_X], "hold": True, "sec": 0.02, "wait": 0.05, "refresh": True}
    LEFT_SHORT_HOP = {"name": "LEFT_SHORT_HOP", "buttons": [Button.BUTTON_S_LEFT, Button.BUTTON_Y, Button.BUTTON_X], "hold": True, "sec": 0.02, "wait": 0.05, "refresh": True}
    UP_TAUNT = {"name": "UP_TAUNT", "buttons": [Button.BUTTON_D_UP], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    DOWN_TAUNT = {"name": "DOWN_TAUNT", "buttons": [Button.BUTTON_D_DOWN], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    LEFT_TAUNT = {"name": "LEFT_TAUNT", "buttons": [Button.BUTTON_D_LEFT], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    RIGHT_TAUNT = {"name": "RIGHT_TAUNT", "buttons": [Button.BUTTON_D_RIGHT], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    SPOT_DODGE = {"name": "SPOT_DODGE", "buttons": [Button.BUTTON_ZR, Button.BUTTON_S_DOWN], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    RIGHT_ROLL = {"name": "RIGHT_ROLL", "buttons": [Button.BUTTON_ZR, Button.BUTTON_S_RIGHT], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    LEFT_ROLL = {"name": "LEFT_ROLL", "buttons": [Button.BUTTON_ZR, Button.BUTTON_S_LEFT], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    RIGHT_DASH = {"name": "RIGHT_DASH", "buttons": [Button.BUTTON_S_RIGHT], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    LEFT_DASH = {"name": "LEFT_DASH", "buttons": [Button.BUTTON_S_LEFT], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    RIGHT_WALK = {"name": "RIGHT_WALK", "buttons": [Button.BUTTON_MODIFIER, Button.BUTTON_S_RIGHT], "hold": True, "sec": 0.02, "wait": 0.05, "refresh": False}
    LEFT_WALK = {"name": "LEFT_WALK", "buttons": [Button.BUTTON_MODIFIER, Button.BUTTON_S_LEFT], "hold": True, "sec": 0.02, "wait": 0.05, "refresh": False}
    CROUCH = {"name": "CROUCH", "buttons": [Button.BUTTON_S_DOWN], "hold": False, "sec": 0.02, "wait": 0.05, "refresh": False}
    RIGHT_CRAWL = {"name": "RIGHT_CRAWL", "buttons": [Button.BUTTON_S_DOWN, Button.BUTTON_MODIFIER, Button.BUTTON_S_RIGHT], "hold": True, "sec": 0.02, "wait": 0.05, "refresh": False}
    LEFT_CRAWL = {"name": "LEFT_CRAWL", "buttons": [Button.BUTTON_S_DOWN, Button.BUTTON_MODIFIER, Button.BUTTON_S_LEFT], "hold": True, "sec": 0.02, "wait": 0.05, "refresh": False}
    RIGHT_STICK = {"name": "RIGHT_STICK", "buttons": [Button.BUTTON_S_RIGHT], "hold": True, "sec": 0.02, "wait": 0.05, "refresh": False}
    LEFT_STICK = {"name": "LEFT_STICK", "buttons": [Button.BUTTON_S_LEFT], "hold": True, "sec": 0.02, "wait": 0.05, "refresh": False}
    UP_STICK = {"name": "UP_STICK", "buttons": [Button.BUTTON_S_UP], "hold": True, "sec": 0.02, "wait": 0.05, "refresh": False}
    DOWN_STICK = {"name": "DOWN_STICK", "buttons": [Button.BUTTON_S_DOWN], "hold": True, "sec": 0.02, "wait": 0.05, "refresh": False}
    
class Action_Old(str, Enum):
    #AIR_ESCAPE = "AIR_ESCAPE"
    UP_TILT = "ATTACK_HI3"
    UP_SMASH = "ATTACK_HI4"
    DOWN_TILT = "ATTACK_LW3"
    DOWN_SMASH = "ATTACK_LW4"
    JAB = "ATTACK_N"
    SIDE_TILT = "ATTACK_S3"
    SIDE_SMASH = "ATTACK_S4"
    GRAB = "CATCH"
    GUARD = "COMMON_GUARD"      # TODO: Implement
    DASH_ATTACK = "DASH_ATTACK"      # TODO: Implement
    DASH = "DASH"
    SPOT_DODGE = "ESCAPE"
    BACK_ROLL = "ESCAPE_B"
    FORWARD_ROLL = "ESCAPE_F"
    JUMP = "JUMP"
    #JUMP_BUTTON = "JUMP_BUTTON"
    #SPECIAL_ANY = "SPECIAL_ANY"
    UP_SPECIAL = "SPECIAL_HI"
    LOW_SPECIAL = "SPECIAL_LW"
    NEUTRAL_SPECIAL = "SPECIAL_N"
    SIDE_SPECIAL = "SPECIAL_S"
    TURN = "TURN"
    TURN_DASH = "TURN_DASH"
    WALK = "WALK"
    #WALL_JUMP_LEFT = "WALL_JUMP_LEFT"
    #WALL_JUMP_RIGHT = "WALL_JUMP_RIGHT"
    NONE = "NONE"
