version: '3'
services:
  libultimate:
    tty: true
    image: deepsmash/libultimate:latest
    privileged: true
    runtime: nvidia
    container_name: libultimate
    ports:
      - "8081:8081" # for novnc
      - "6006:6006" # for tensorboard
      - "6000:6000" # for yuzu api
    volumes:
      - "/Users/ruihirano/MyProjects/DeepSmashProject/:/workspace"
      - "/Users/ruihirano/MyProjects/DeepSmashProject/data/keys:/root/.local/sh\
        are/yuzu/keys"
    environment:
      - "RESOLUTION=1280x800"
      - "VNCPASS=pass"
      - "DISPLAY=:1"
      - "BUS_ID=13:0:0"
      - "NOVNC_PORT=8081"
      - "API_HOST=0.0.0.0"
      - "API_PORT=6000"
      - "API_FILE_PATH=/workspace/libultimate/run_server.py"
