version: '3.5'
services:
  ubuntu-20.04-desktop:
    image: deepsmash/libultimate:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libultimate
    runtime: nvidia
    ports:
      - ${NOVNC_PORT}:6080
      - 8008:8008 # port for api
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - ${GAME_DIR}:/root/data/games
      - ${FIRMWARE_DIR}:/root/data/firmware
      - ${PRODKEYS_DIR}:/root/data/keys
    cap_add:
      - SYS_BOOT
      - SYS_ADMIN
