from yuzulib import Runner, Screen
from libultimate import Controller, Action
import time
import random
runner = Runner("", "", "")
runner.run()

controller = Controller()

print("Action JAB")
controller.act(Action.ACTION_JAB)
time.sleep(1)

print("Action RIGHT TILT")
controller.act(Action.ACTION_RIGHT_TILT)
time.sleep(1)
print("Action LEFT TILT")
controller.act(Action.ACTION_LEFT_TILT)
time.sleep(1)
print("Action UP TILT")
controller.act(Action.ACTION_UP_TILT)
time.sleep(1)
print("Action DOWN TILT")
controller.act(Action.ACTION_DOWN_TILT)
time.sleep(1)

print("Action NEUTRAL SPECIAL")
controller.act(Action.ACTION_NEUTRAL_SPECIAL)
time.sleep(1)
print("Action RIGHT SPECIAL")
controller.act(Action.ACTION_RIGHT_SPECIAL)
time.sleep(1)
print("Action LEFT SPECIAL")
controller.act(Action.ACTION_LEFT_SPECIAL)
time.sleep(1)
print("Action UP SPECIAL")
controller.act(Action.ACTION_UP_SPECIAL)
time.sleep(1)
print("Action DOWN SPECIAL")
controller.act(Action.ACTION_DOWN_SPECIAL)
time.sleep(1)


print("Action RIGHT SMASH")
controller.act(Action.ACTION_RIGHT_SMASH)
time.sleep(1)
print("Action LEFT SMASH")
controller.act(Action.ACTION_LEFT_SMASH)
time.sleep(1)
print("Action UP SMASH")
controller.act(Action.ACTION_UP_SMASH)
time.sleep(1)
print("Action DOWN SMASH")
controller.act(Action.ACTION_DOWN_SMASH)
time.sleep(1)


print("Action JUMP")
controller.act(Action.ACTION_JUMP)
time.sleep(1)
print("Action SHORT HOP")
controller.act(Action.ACTION_SHORT_HOP)
time.sleep(1)
print("Action GRAB")
controller.act(Action.ACTION_GRAB)
time.sleep(1)


print("Action RIGHT DASH")
controller.act(Action.ACTION_RIGHT_DASH)
time.sleep(1)
print("Action LEFT DASH")
controller.act(Action.ACTION_LEFT_DASH)
time.sleep(1)
print("Action RIGHT WALK")
controller.act(Action.ACTION_RIGHT_WALK)
time.sleep(1)
print("Action LEFT WALK")
controller.act(Action.ACTION_LEFT_WALK)
time.sleep(1)
print("Action CROUCH")
controller.act(Action.ACTION_CROUCH)
time.sleep(1)
print("Action RIGHT CRAWL")
controller.act(Action.ACTION_RIGHT_CRAWL)
time.sleep(1)
print("Action LEFT CRAWL")
controller.act(Action.ACTION_LEFT_CRAWL)
time.sleep(1)


print("Action SHIELD")
controller.act(Action.ACTION_SHIELD)
time.sleep(1)
print("Action SPOT_DODGE")
controller.act(Action.ACTION_SPOT_DODGE)
time.sleep(1)
print("Action RIGHT ROLL")
controller.act(Action.ACTION_RIGHT_ROLL)
time.sleep(1)
print("Action LEFT ROLL")
controller.act(Action.ACTION_LEFT_ROLL)
time.sleep(1)


print("Action RIGHT TAUNT")
controller.act(Action.ACTION_RIGHT_TAUNT)
time.sleep(1)
print("Action LEFT TAUNT")
controller.act(Action.ACTION_LEFT_TAUNT)
time.sleep(1)
print("Action UP TAUNT")
controller.act(Action.ACTION_UP_TAUNT)
time.sleep(1)
print("Action DOWN TAUNT")
controller.act(Action.ACTION_DOWN_TAUNT)
time.sleep(1)


print("Action RIGHT STICK")
controller.act(Action.ACTION_RIGHT_STICK)
time.sleep(1)
print("Action LEFT STICK")
controller.act(Action.ACTION_LEFT_STICK)
time.sleep(1)
print("Action UP STICK")
controller.act(Action.ACTION_UP_STICK)
time.sleep(1)
print("Action DOWN STICK")
controller.act(Action.ACTION_DOWN_STICK)
time.sleep(1)
print("Action NO OPERATION")
controller.act(Action.ACTION_NO_OPERATION)
time.sleep(1)