# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/libultimate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/libultimate.proto\x12\x0blibultimate\"\x1c\n\tGameState\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\x0eGameStateProps\x12\n\n\x02hz\x18\x01 \x01(\x04\"\x1f\n\x0c\x43ontrolProps\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\rControlResult\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa4\x01\n\x0bLibUltimate\x12L\n\x11OperateController\x12\x19.libultimate.ControlProps\x1a\x1a.libultimate.ControlResult\"\x00\x12G\n\x0cGetGameState\x12\x1b.libultimate.GameStateProps\x1a\x16.libultimate.GameState\"\x00\x30\x01\x42\x32\n\x1cio.grpc.examples.libultimateB\x10LibUltimateProtoP\x01\x62\x06proto3')



_GAMESTATE = DESCRIPTOR.message_types_by_name['GameState']
_GAMESTATEPROPS = DESCRIPTOR.message_types_by_name['GameStateProps']
_CONTROLPROPS = DESCRIPTOR.message_types_by_name['ControlProps']
_CONTROLRESULT = DESCRIPTOR.message_types_by_name['ControlResult']
GameState = _reflection.GeneratedProtocolMessageType('GameState', (_message.Message,), {
  'DESCRIPTOR' : _GAMESTATE,
  '__module__' : 'proto.libultimate_pb2'
  # @@protoc_insertion_point(class_scope:libultimate.GameState)
  })
_sym_db.RegisterMessage(GameState)

GameStateProps = _reflection.GeneratedProtocolMessageType('GameStateProps', (_message.Message,), {
  'DESCRIPTOR' : _GAMESTATEPROPS,
  '__module__' : 'proto.libultimate_pb2'
  # @@protoc_insertion_point(class_scope:libultimate.GameStateProps)
  })
_sym_db.RegisterMessage(GameStateProps)

ControlProps = _reflection.GeneratedProtocolMessageType('ControlProps', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLPROPS,
  '__module__' : 'proto.libultimate_pb2'
  # @@protoc_insertion_point(class_scope:libultimate.ControlProps)
  })
_sym_db.RegisterMessage(ControlProps)

ControlResult = _reflection.GeneratedProtocolMessageType('ControlResult', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLRESULT,
  '__module__' : 'proto.libultimate_pb2'
  # @@protoc_insertion_point(class_scope:libultimate.ControlResult)
  })
_sym_db.RegisterMessage(ControlResult)

_LIBULTIMATE = DESCRIPTOR.services_by_name['LibUltimate']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034io.grpc.examples.libultimateB\020LibUltimateProtoP\001'
  _GAMESTATE._serialized_start=40
  _GAMESTATE._serialized_end=68
  _GAMESTATEPROPS._serialized_start=70
  _GAMESTATEPROPS._serialized_end=98
  _CONTROLPROPS._serialized_start=100
  _CONTROLPROPS._serialized_end=131
  _CONTROLRESULT._serialized_start=133
  _CONTROLRESULT._serialized_end=165
  _LIBULTIMATE._serialized_start=168
  _LIBULTIMATE._serialized_end=332
# @@protoc_insertion_point(module_scope)
