name: Build and push Docker image to GHCR

on:
  # Trigger the workflow when a new tag is pushed
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set env
        run: echo "COMMIT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          dockerfile: ./docker/Dockerfile
          push: true
          tags: ghcr.io/deepsmash/libultimate:${{ env.COMMIT_TAG }}